### ISSUE TITLE
用Typescript开发，代码提示功能

### ISSUE THREAD

**Issue by candyguy242** [youngjuning/wxPromise#26]
现在用Typescripte做项目，VScode总是提示：类型“WX”上不存在属性“pro。
期待能出一个VSCode的代码提示文件。
另外项目中使用npm方式引入的库，然后使用如下 ：

import 'wx-promise-pro';
onLoad(){
    wx.pro.request({
      url: 'https://cnodejs.org/api/v1/topics',
      data: {},
      method: 'GET',
      header: {'content-type': 'application/json'}
    }).then(res => {
      console.log(res)
    }).catch(err => {
      console.log(err)
    }).finally(() => {
      wx.hideLoading({});
    })
}

可是运行起来报如下错误：
VM4219:1 thirdScriptError 
 sdk uncaught third Error 
 module "pages/index/wx-promise-pro" is not defined 
 Error: module "pages/index/wx-promise-pro" is not defined
    at require (http://127.0.0.1:18812/appservice/__dev__/WAService.js:1:716408)
    at http://127.0.0.1:18812/appservice/__dev__/WAService.js:1:716158
    at http://127.0.0.1:18812/appservice/pages/index/index.js:4:1
    at require (http://127.0.0.1:18812/appservice/__dev__/WAService.js:1:716549)
    at <anonymous>:8:7
    at HTMLScriptElement.scriptLoaded (

请指点一下，谢谢

**Comment by candyguy242** [comment]
上面运行报错的原因已找到，是因为TypeScript默认不引入js文件进行编译，通过修改配置正常了。有同样问题的人可以参考：https://blog.csdn.net/candyguy242/article/details/84619884
